apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: test-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Test is the Schema for the tests API
      displayName: Test
      kind: Test
      name: tests.test.my.domain
      version: v1
  description: test operator with packagemanifests
  displayName: test-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - jesusr@redhat.com
  links:
  - name: Test Operator
    url: https://test-operator.domain
  maturity: alpha
  provider:
    name: zeusville
  version: 0.0.0
